<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Compositor.MaskEffects</RootNamespace>
    <AssemblyName>Compositor.MaskEffects</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compositor.Adjust\Compositor.Adjust.csproj" />
    <ProjectReference Include="..\Compositor.Core\Compositor.Core.csproj" />
  </ItemGroup>

</Project>